name: Build and deploy ASP.Net Core app to Azure Web App - Assignment3-Ticket-Hub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish TicketHubAPI/TicketHubAPI.csproj -c Release -o ${{ github.workspace }}/publish

      - name: List files in publish directory
        run: dir ${{ github.workspace }}/publish  # List the files to verify the output directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Assignment3-Ticket-Hub'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish  # The publish directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BEC2B75E1F9E4C6688A7D20B5B63829D }}
